### ISSUE TITLE
Importing harnessmaker requires act file else gives ValueError

### ISSUE THREAD

**Issue by pramttl** [pramttl/tstl#5]
Importing harnessmaker should not require act file. Currently the following error results when harnessmaker is imported `ValueError: The .act file is not specified`. It makes it hard to import harnessmaker in a tests file to test the code within it. Only time when act file should be required is when harnessmaker is explicitly run by using `python harnessmaker.py` ...

**Solution**: Code needs refactoring code into main() and separating the functions out.

```
(venv)pranjal:~/projects/ase_cs562/tstl/src$ python
Python 2.7.8 (default, Oct 19 2014, 16:02:00)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import harnesmaker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named harnesmaker
>>> import harnessmaker
usage: [-h] [-a ACT] [-t TARGET] [-c CLASSNAME] [-n] [-r] [-i]

optional arguments:
  -h, --help            show this help message and exit
  -a ACT, --act ACT     Path to the .act file.
  -t TARGET, --target TARGET
                        Name of the file containing the generated harness core
                        (default = sut.py)
  -c CLASSNAME, --classname CLASSNAME
                        Name of the class representing the SUT (default=t)
  -n, --nocover         Disable generating coverage collection support.
  -r, --coverreload     Generate coverage for module reload behavior.
  -i, --coverinit       Generate coverage for SUT initialization behavior.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "harnessmaker.py", line 56, in <module>
    config = make_config(parsed_args, parser)
  File "harnessmaker.py", line 38, in make_config
    raise ValueError('The .act file is not specified.')
ValueError: The .act file is not specified.
>>>
```

**Comment by pramttl** [comment]
Solved now!
